# frozen_string_literal: true

task setup: %w[setup:clean setup:webui setup:python]

task "setup:clean" do
  require "fileutils"

  FileUtils::Verbose.rm_rf "tmp"
  FileUtils::Verbose.mkdir_p "tmp"

  Dir
    .glob("../zundamon_speech/*")
    .each do |dir|
      next if %w[.gitkeep server].include? File.basename(dir)

      FileUtils::Verbose.rm_rf dir
    end
end

task "setup:webui" do
  sh "git lfs install"
  sh "git submodule update --init --recursive"

  sh "curl https://paddlespeech.bj.bcebos.com/Parakeet/released_models/g2p/G2PWModel_1.1.zip -Lfo tmp/G2PWModel_1.1.zip"
  sh "unzip -o tmp/G2PWModel_1.1.zip -d tmp"

  webui_dir = "../zundamon_speech/zundamon-speech-webui"

  FileUtils::Verbose.rm_rf webui_dir
  FileUtils::Verbose.mkdir_p webui_dir
  FileUtils::Verbose.cp_r "./zundamon-speech-webui/.", webui_dir

  inference_webui_py = "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/inference_webui.py"
  inference_webui_py_content = File.read(inference_webui_py)
  File.write(
    inference_webui_py,
    inference_webui_py_content.gsub(
      'dict_s2 = torch.load(sovits_path, map_location="cpu")',
      'dict_s2 = torch.load(sovits_path, map_location="cpu", weights_only=False)'
    )
  )

  FileUtils::Verbose.cp_r "./GPT-SoVITS/.",
                          "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/pretrained_models"

  FileUtils::Verbose.mkdir_p "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/pretrained_models/G2PWModel"
  FileUtils::Verbose.cp_r "tmp/G2PWModel_1.1/.",
                          "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/pretrained_models/G2PWModel"

  FileUtils::Verbose.mkdir_p "../zundamon_speech/zundamon_GPT-SoVITS"
  FileUtils::Verbose.cp_r "./zundamon_GPT-SoVITS/.",
                          "../zundamon_speech/zundamon_GPT-SoVITS"
end

task "setup:python" do
  require "fileutils"
  require "rbconfig"

  os =
    case RbConfig::CONFIG["host_os"]
    when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
      "windows"
    when /darwin|mac os/
      "macosx"
    when /linux/
      "linux"
    else
      raise "unknown os: #{RbConfig::CONFIG["host_os"]}"
    end

  arch = RbConfig::CONFIG["host_cpu"]

  triplet =
    case [arch, os]
    in ["x86_64", "windows"]
      "x86_64-pc-windows-msvc"
    in ["x86_64", "macosx"]
      "x86_64-apple-darwin"
    in ["x86_64", "linux"]
      "x86_64-unknown-linux-gnu"
    else
      raise "unknown triplet: #{arch} #{os}"
    end

  version = "3.9.21"
  build_version = "20250212"

  url =
    "https://github.com/astral-sh/python-build-standalone/releases/download/#{build_version}/cpython-#{version}+#{build_version}-#{triplet}-install_only_stripped.tar.gz"

  sh "curl -Lfo tmp/python.tar.gz #{url}"
  sh "tar -xzf tmp/python.tar.gz -C tmp"

  FileUtils::Verbose.mkdir_p "../zundamon_speech/standalone_python"
  FileUtils::Verbose.cp_r "tmp/python/.", "../zundamon_speech/standalone_python"

  Dir.chdir "../zundamon_speech/zundamon-speech-webui" do
    index_url =
      if ENV["ZTS_DEVICE"] == "cuda"
        "https://download.pytorch.org/whl/cu121"
      else
        "https://download.pytorch.org/whl/cpu"
      end
    sh "../standalone_python/bin/python3 -m pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url #{index_url}"
    sh "../standalone_python/bin/python3 -m pip install -r requirements.txt"
    sh "../standalone_python/bin/python3 -m pip install -r ../server/requirements.txt"
  end
end
