# frozen_string_literal: true

task setup: %w[setup:clean setup:webui setup:python setup:ffmpeg]

task "setup:clean" do
  require "fileutils"

  FileUtils::Verbose.rm_rf "tmp"
  FileUtils::Verbose.mkdir_p "tmp"

  Dir
    .glob("../zundamon-speech/*")
    .each do |dir|
      next if %w[.gitkeep server].include? File.basename(dir)

      FileUtils::Verbose.rm_rf dir
    end
end

task "setup:webui" do
  sh "git lfs install"
  sh "git submodule update --init --recursive"

  sh "curl https://paddlespeech.bj.bcebos.com/Parakeet/released_models/g2p/G2PWModel_1.1.zip -Lfo tmp/G2PWModel_1.1.zip"
  sh "unzip -o tmp/G2PWModel_1.1.zip -d tmp"

  webui_dir = "../zundamon-speech/zundamon-speech-webui"

  FileUtils::Verbose.rm_rf webui_dir
  FileUtils::Verbose.mkdir_p webui_dir
  FileUtils::Verbose.cp_r "./zundamon-speech-webui/.", webui_dir

  inference_webui_py = "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/inference_webui.py"
  inference_webui_py_content = File.read(inference_webui_py)
  File.write(
    inference_webui_py,
    inference_webui_py_content.gsub(
      'dict_s2 = torch.load(sovits_path, map_location="cpu")',
      'dict_s2 = torch.load(sovits_path, map_location="cpu", weights_only=False)'
    )
  )

  FileUtils::Verbose.cp_r "./GPT-SoVITS/.",
                          "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/pretrained_models"

  FileUtils::Verbose.mkdir_p "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/pretrained_models/G2PWModel"
  FileUtils::Verbose.cp_r "tmp/G2PWModel_1.1/.",
                          "#{webui_dir}/GPT-SoVITS/GPT_SoVITS/pretrained_models/G2PWModel"

  FileUtils::Verbose.mkdir_p "../zundamon-speech/zundamon_GPT-SoVITS"
  FileUtils::Verbose.cp_r "./zundamon_GPT-SoVITS/.",
                          "../zundamon-speech/zundamon_GPT-SoVITS"
end

task "setup:python" do
  require "fileutils"
  require "rbconfig"

  os =
    case RbConfig::CONFIG["host_os"]
    when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
      "windows"
    when /darwin|mac os/
      "macosx"
    when /linux/
      "linux"
    else
      raise "unknown os: #{RbConfig::CONFIG["host_os"]}"
    end

  arch = RbConfig::CONFIG["host_cpu"]

  triplet =
    case [arch, os]
    in ["x64", "windows"]
      "x86_64-pc-windows-msvc"
    in ["arm64", "macosx"]
      "aarch64-apple-darwin"
    in ["x86_64", "linux"]
      "x86_64-unknown-linux-gnu"
    else
      raise "unknown triplet: #{arch} #{os}"
    end

  version = "3.9.21"
  build_version = "20250212"

  url =
    "https://github.com/astral-sh/python-build-standalone/releases/download/#{build_version}/cpython-#{version}+#{build_version}-#{triplet}-install_only_stripped.tar.gz"

  sh "curl -Lfo tmp/python.tar.gz #{url}"
  sh "tar -xzf tmp/python.tar.gz -C tmp"

  FileUtils::Verbose.mkdir_p "../zundamon-speech/standalone_python"
  FileUtils::Verbose.cp_r "tmp/python/.", "../zundamon-speech/standalone_python"

  Dir.chdir "../zundamon-speech/zundamon-speech-webui" do
    index_url =
      if ENV["ZTS_DEVICE"] == "cuda"
        "https://download.pytorch.org/whl/cu121"
      else
        "https://download.pytorch.org/whl/cpu"
      end
    python_bin = os == "windows" ? "python" : "bin/python3"
    sh "../standalone_python/#{python_bin} -m pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url #{index_url}"
    if ENV["ZTS_DEVICE"] != "cuda"
      requirements = File.read("requirements.txt")
      requirements.gsub!("onnxruntime-gpu", "# onnxruntime-gpu")
      File.write("requirements.txt", requirements)
    end
    sh "../standalone_python/#{python_bin} -m pip install -r requirements.txt --no-compile --no-cache-dir"
    sh "../standalone_python/#{python_bin} -m pip install -r ../server/requirements.txt --no-compile --no-cache-dir"
    sh "../standalone_python/#{python_bin} -m pip uninstall -y modelscope matplotlib streamlit fonttools"

    lib_root =
      (
        if os == "windows"
          "../standalone_python/Lib"
        else
          "../standalone_python/lib/python3.9"
        end
      )

    FileUtils::Verbose.rm_rf "#{lib_root}/share/jupyter"
    FileUtils::Verbose.rm_rf "#{lib_root}/ensurepip"
    Dir
      .glob("#{lib_root}/**/*.{pyc,h,cpp,hpp,c}")
      .each { |file| FileUtils::Verbose.rm_r file if File.exist? file }
    Dir
      .glob("#{lib_root}/__pycache__")
      .each { |file| FileUtils::Verbose.rm_r file if File.exist? file }
    Dir
      .glob("#{lib_root}/**/tests")
      .each { |file| FileUtils::Verbose.rm_r file }

    scripts_root =
      (
        if os == "windows"
          "../standalone_python/Scripts"
        else
          "../standalone_python/bin"
        end
      )

    files = Dir.glob("#{scripts_root}/*")
    files.reject! { |file| File.basename(file).include? "python" }

    FileUtils::Verbose.rm_rf files
  end
end

task "setup:ffmpeg" do
  if RbConfig::CONFIG["host_os"] =~ /mswin|msys|mingw|cygwin|bccwin|wince|emc/
    sh "curl -Lfo tmp/ffmpeg.exe https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/ffmpeg.exe"
    sh "curl -Lfo tmp/ffprobe.exe https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/ffprobe.exe"

    FileUtils::Verbose.cp "tmp/ffmpeg.exe",
                          "../zundamon-speech/zundamon-speech-webui/GPT-SoVITS/ffmpeg.exe"
    FileUtils::Verbose.cp "tmp/ffprobe.exe",
                          "../zundamon-speech/zundamon-speech-webui/GPT-SoVITS/ffprobe.exe"
  end
end
